version: '2'

services:

  wekan:
    image: wekanteam/wekan:latest
    container_name: wekan-app
    networks:
        - wekan-tier
    ports:
        - 8081:80
    links:
        - wekandb
    environment:
        - MONGO_URL=mongodb://wekandb/wekan
        - ROOT_URL=http://localhost:8081

  wekandb:
    image: mongo:3.2.14
    container_name: wekan-db
    networks:
        - wekan-tier
    expose:
        - 27017
    volumes:
      - /home/miro/Apps/docker/wekan/data:/data/db

networks:
    wekan-tier:
        driver: bridge
